config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /pt-BR|es|en/ do
    root :to => 'home#index'
    get "home/index"
  end

  resources :medias

  devise_for :users
  resources :users

  get 'home/index'
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/media.rb
class Media < ApplicationRecord
  belongs_to :user

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :media_type, presence: true

  has_attached_file :file
  do_not_validate_attachment_file_type  :file
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :medias

  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_attached_file :photo, styles: { medium: "360x360>", thumb: "180x180>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected
    def set_locale
      I18n.default_locale = "pt-BR"
      I18n.locale = params[:locale] || I18n.default_locale
      Rails.application.routes.default_url_options[:locale] = I18n.locale
     end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    def check_owner(user_id)
      if signed_in?
        if ! current_user.admin? && current_user.id != (user_id)
          redirect_to root_url, alert: "Permission Denied"
        end
      end
    end

    def check_if_admin
      if signed_in?
        if ! current_user.admin?
          redirect_to root_url, alert: "Permission Denied"
        end
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/medias_controller.rb
class MediasController < ApplicationController
  before_action :set_media, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action -> { check_owner Media.friendly.find(params[:id]).user_id }, only: [:edit, :update, :destroy]
  before_action :load_media_types, except: [:index, :show]

  # GET /medias
  # GET /medias.json
  def index
    @medias = Media.all.sort_by(&:updated_at).reverse
  end

  # GET /medias/1
  # GET /medias/1.json
  def show
  end

  # GET /medias/new
  def new
    @media = Media.new
  end

  # GET /medias/1/edit
  def edit
  end

  # POST /medias
  # POST /medias.json
  def create
    @media = Media.new(media_params)

    if ! current_user.admin?
      @media.user_id = current_user.id
    end

    respond_to do |format|
      if @media.save
        format.html { redirect_to @media, notice: 'Media foi cadastrado.' }
        format.json { render :show, status: :created, location: @media }
      else
        format.html { render :new }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medias/1
  # PATCH/PUT /medias/1.json
  def update
    respond_to do |format|
      if @media.update(media_params)
        format.html { redirect_to @media, notice: 'Media foi atualizado.' }
        format.json { render :show, status: :ok, location: @media }
      else
        format.html { render :edit }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medias/1
  # DELETE /medias/1.json
  def destroy
    @media.destroy
    respond_to do |format|
      format.html { redirect_to medias_url, notice: 'Media foi removido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media
      @media = Media.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def media_params
      params.require(:media).permit(:media_type, :title, :author, :description, :slug, :user_id, :file)
    end

    def load_media_types
      @media_types = { "Audio"  => "Audio",
                 "Video"  => "Video",
                 "Texto"  => "Text",
                 "Imagem" => "Image"
               }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action -> { check_owner User.friendly.find(params[:id]).id }, only: [:edit, :update, :destroy]

  def index
    @users = User.all.sort_by(&:updated_at).reverse
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was removed." }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.friendly.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:id, :email, :name, :slug, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_alert.html.erb
        <% if notice %>
          <div class="alert alert-info fade in" role="alert">
            <%= notice %>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger fade in" role="alert">
            <%= alert %>
          </div>
        <% end %>

app/views/layouts/_footer.html.erb
    <br/><br/><br/><br/><br/><br/><br/>
    <footer class="footer">
      <div class="container">
        <span class="text-muted">
          <%= link_to I18n.t(:estudiolivre_is_free_software), "https://gitlab.com/marcelo-soares-souza/estudiolivre", :target => "_blank" %>
        </span>
      </div>
    </footer>

app/views/layouts/_main.html.erb
<div class="container">
  <div class="starter-template">
    <% if notice or alert%>
      <%= render 'layouts/alert' %>
    <% end %>
    <%= yield %>
  </div>
</div>

app/views/layouts/_menu.html.erb
  <script>
    $(document).ready(function() {
      $("#locale").val("<%= locale %>");
    });
  </script>

  <nav class="navbar navbar-toggleable-md navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        &#9776;
      </button>

      <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to(image_tag("estudiolivre-small.png", :width => "150"), root_path, :class => "nav-link", :target => "_blank") %>
          </li>

          <li class="nav-item"><br/>
            <%= link_to(I18n.t(:about), root_path, :class => "nav-link") %>
          </li>

          <li class="nav-item"><br/>
            <%= link_to(I18n.t(:medias), medias_path, :class => "nav-link") %>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to("#{I18n.t(:logout)}", destroy_user_session_path, :method => :delete, :class => "nav-link") %>
            </li>

            <li class="nav-item">
              <%= link_to "(#{current_user.email})", user_path(current_user), :class => "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to(I18n.t(:login), new_user_session_path, :class => "nav-link") %>
            </li>
            <li>
              <strong><%= link_to I18n.t(:register), new_user_registration_path, :class => "nav-link text-danger" %></strong>
            </li>

          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <select id="locale" onchange="if (this.value) window.location.href='/?locale=' + this.value" class="form-control">
                <option value="pt-BR">Português</option>
                <option value="es">Español</option>
                <option value="en">English</option>
              </select>
            </li>
          </ul>
        </ul>

      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= CONFIG['lang'] %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="<%= image_url "favicon.ico" %>">

    <title><%= CONFIG['title'] %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= render 'layouts/menu' %>
    <%= render 'layouts/main' %>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/medias/_form.html.erb
<%= form_for(media, html: { multipart: true }) do |f| %>
  <% if media.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(media.errors.count, "error") %> encontrado(s):</h2>

      <ul>
      <% media.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin? %>
    <div class="form-group row">
      <%= f.label I18n.t(:responsable), class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.collection_select(:user_id, User.all, :id, :name,  {}, { class: "form-control selectpicker", "data-live-search": true } ) %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label I18n.t(:title), class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label I18n.t(:description), class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label I18n.t(:author), class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_field :author, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label I18n.t(:media_type), class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.collection_select(:media_type, @media_types, :last, :first,  { :include_blank => 'Selecione um Tipo de Media' }, { class: "form-control selectpicker", "data-live-search": true } ) %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label I18n.t(:file), class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-8">
      <%= f.file_field :file, class: "form-control" %>
    </div>
  </div>

  <br/>

  <div class="actions">
    <%= f.submit t(:submit), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/medias/edit.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to I18n.t(:medias), medias_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:edit)} #{@media.title}", edit_media_path(@media), :class => "nav-link active" %>
  </li>
</ul>
<br/>
<%= render 'form', media: @media %>

app/views/medias/index.html.erb
<%= link_to I18n.t(:new), new_media_path, :class => "btn btn-primary", :style => "float:right;" %>
<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to I18n.t(:medias), medias_path, :class => "nav-link active" %>
  </li>
</ul>

<% if @medias.empty? %>
  <br/>
  <h3>Nenhuma Media</h3>
<% else %>

  <br/>
  <div style="overflow-x:auto;">
    <table id="dataTable-el" class="table table-striped table-bordered" width="100%" cellspacing="0">
      <thead>
        <tr>
          <!-- <th></th> -->
          <th>Title</th>
          <th>Media Type</th>
          <th>Download</th>
          <th>Published</th>
          <% if user_signed_in? %><th class="list-control"></th><th class="list-control"></th><% end %>
        </tr>
      </thead>

      <tbody>
        <% @medias.each do |media| %>
        <tr>
          <!-- <td scope="row"><%= link_to image_tag(media.file.url(:thumb), :width => "120", :height => "120"), media_path(media) %></td> -->
          <td><%= link_to truncate(media.title, length: 128), media_path(media) %></td>
          <td><%= media.media_type %></td>
          <td><%= link_to 'Download', media.file.url if media.file? %></td>
          <td><%= media.created_at %></td>

          <% if user_signed_in? %>
            <% if current_user.admin? or media.user.id == current_user.id %>
              <td><%= link_to t(:edit), edit_media_path(media), :class => 'btn btn-sm btn-success' %></td>
              <td><%= link_to t(:destroy), media_path(media), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
            <% end %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <script>$(document).ready(function(){ dataTables(); });</script>
<% end %>

app/views/medias/new.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to I18n.t(:medias), medias_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:new), new_media_path, :class => "nav-link active" %>
  </li>
</ul>

<br/>

<%= render 'form', media: @media %>

app/views/medias/show.html.erb
<%= link_to I18n.t(:new), new_media_path, :class => "btn btn-primary", :style => "float:right;" %>
<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to I18n.t(:medias), medias_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to @media.title, media_path(@media.id), :class => "nav-link active" %>
  </li>
</ul>

<br/>

<div class="tab-content" style="min-height: 64px;">
  <div class="tab-pane active">
    <center>
      <h3><%= @media.title %></h3>
      <%= link_to 'Download', @media.file.url if @media.file?%>

      <br/><br/>
      <%= "<strong>Media Type:</strong><br/>#{@media.media_type}&nbsp;".html_safe if @media.media_type? %>
      <%= "<br/><br/><strong>Description:</strong><br/>#{@media.description}&nbsp;".html_safe if @media.description? %>
      <%= "<br/><br/><strong>Author:</strong><br/>#{@media.author}&nbsp;".html_safe if @media.author? %>
      <%= "<br/><br/><strong>#{I18n.t(:responsable)}:</strong><br/>#{link_to @media.user.name, user_path(@media.user)}&nbsp;".html_safe if @media.user.name?%>

    </center>
    </div>
</div>

<% if user_signed_in? %>
  <% if current_user.admin? or current_user.id == @media.user.id %>        
    <br/><br/>
    <div class="form-actions">
      <%= link_to t('.edit', :default => "Editar"), edit_media_path(@media), :class => 'btn btn-success' %>
      <%= link_to t(:destroy), media_path(@media), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-danger' %>
    </div>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user, html: { multipart: true }) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> encontrado(s):</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label 'Nome', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'E-Mail', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Imagem", class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-8">
      <%= f.file_field :photo, class: "form-control" %>
    </div>
  </div>

  <br/>
  <div class="actions">
    <%= f.submit t(:submit), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), users_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:edit)} #{@user.name}", edit_user_path(@user), :class => "nav-link active" %>
  </li>
</ul>
<br/>
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), users_path, :class => "nav-link active" %>
  </li>
</ul>

<% if @users.empty? %>
  <br/>
  <h3>Nenhum Usuário Registrado</h3>
<% else %>

  <br/>
  <div style="overflow-x:auto;">
    <table id="dataTable-el" class="table table-striped table-bordered" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th></th>
          <th>Nome</th>
          <th>E-Mail</th>
          <% if user_signed_in? %><th class="list-control"></th><th class="list-control"></th><% end %>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td scope="row"><%= link_to image_tag(user.photo.url(:thumb), :width => "100", :height => "100"), user_path(user) %></td>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= truncate(user.email, length: 64) %></td>
          <% if user_signed_in? %>
            <% if current_user.admin? or user.id == current_user.id %>
                <td><%= link_to t(:edit), edit_user_path(user), :class => 'btn btn-sm btn-success' %></td>
                <% if current_user.admin? %>
                  <td><%= link_to t(:destroy), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' if user.id != 1 %></td>
                <% end %>
            <% else %>
              <td></td>
            <% end %>
          <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <script>$(document).ready(function(){ dataTables(); });</script>
<% end %>

app/views/users/show.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), users_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to @user.name, user_path(@user.id), :class => "nav-link active" %>
  </li>
</ul>

<br/>

<div class="tab-content" style="min-height: 64px;">
  <div class="tab-pane active">
    <center>
      <%= image_tag(@user.photo.url(:medium), :width => "150") %>

      <br/><br/>
      <h3><%= @user.name %></h3>

      <br/>
      <%= "<strong>E-Mail:</strong><br/>#{@user.email}&nbsp;".html_safe if @user.email?%>
    </center>
  </div>
</div>

<% if user_signed_in? %>
  <% if current_user.admin? or current_user.id == @user.id %>        
    <br/><br/>
    <div class="form-actions">
      <%= link_to t('.edit', :default => "Editar"), edit_user_path(@user), :class => 'btn btn-success' %>
      <% if current_user.admin? %>
        <%= link_to t(:destroy), user_path(@user), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-danger' if @user.id != 1 %>
      <% end %>
    </div>
  <% end %>
<% end %>